// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: flow.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Texas.Protocol {

  /// <summary>Holder for reflection information generated from flow.proto</summary>
  public static partial class FlowReflection {

    #region Descriptor
    /// <summary>File descriptor for flow.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FlowReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpmbG93LnByb3RvKnkKEEZsb3dDdXJyZW5jeVR5cGUSEQoNQ1VSUkVOQ1lf",
            "Tk9ORRAAEhEKDUNVUlJFTkNZX0dPTEQQARIUChBDVVJSRU5DWV9ESUFNT05E",
            "EAISFAoQQ1VSUkVOQ1lfUFBDSElQUxADEhMKD0NVUlJFTkNZX1JFQkFURRAE",
            "QhhaBS9nb3BiqgIOVGV4YXMuUHJvdG9jb2xiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Texas.Protocol.FlowCurrencyType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum FlowCurrencyType {
    [pbr::OriginalName("CURRENCY_NONE")] CurrencyNone = 0,
    /// <summary>
    ///金币
    /// </summary>
    [pbr::OriginalName("CURRENCY_GOLD")] CurrencyGold = 1,
    /// <summary>
    ///钻石
    /// </summary>
    [pbr::OriginalName("CURRENCY_DIAMOND")] CurrencyDiamond = 2,
    /// <summary>
    ///PP币
    /// </summary>
    [pbr::OriginalName("CURRENCY_PPCHIPS")] CurrencyPpchips = 3,
    /// <summary>
    ///积分
    /// </summary>
    [pbr::OriginalName("CURRENCY_REBATE")] CurrencyRebate = 4,
  }

  #endregion

}

#endregion Designer generated code
