// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: promotions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Texas.Protocol {

  /// <summary>Holder for reflection information generated from promotions.proto</summary>
  public static partial class PromotionsReflection {

    #region Descriptor
    /// <summary>File descriptor for promotions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PromotionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBwcm9tb3Rpb25zLnByb3RvIosBCglQcml6ZUl0ZW0SGQoMcHJvbW90aW9u",
            "X2lkGAEgASgFSACIAQESGgoNcHJpemVfaXRlbV9pZBgCIAEoBUgBiAEBEhYK",
            "CWl0ZW1fbmFtZRgDIAEoCUgCiAEBQg8KDV9wcm9tb3Rpb25faWRCEAoOX3By",
            "aXplX2l0ZW1faWRCDAoKX2l0ZW1fbmFtZSJDChVQcm9tb3Rpb25MZWZ0VGlt",
            "ZXNSRVESGQoMcHJvbW90aW9uX2lkGAEgASgFSACIAQFCDwoNX3Byb21vdGlv",
            "bl9pZCKFAQoVUHJvbW90aW9uTGVmdFRpbWVzUlNQEhkKDHByb21vdGlvbl9p",
            "ZBgBIAEoBUgAiAEBEhcKCmxlZnRfdGltZXMYAiABKA1IAYgBARIQCgN1aWQY",
            "AyABKANIAogBAUIPCg1fcHJvbW90aW9uX2lkQg0KC19sZWZ0X3RpbWVzQgYK",
            "BF91aWQipQEKFVJlY2VpdmNlTGVmdFRpbWVzUHVzaBIZCgxwcm9tb3Rpb25f",
            "aWQYASABKAVIAIgBARISCgV0aW1lcxgCIAEoDUgBiAEBEhAKA3VpZBgDIAEo",
            "A0gCiAEBEhgKC3RvdGFsX3RpbWVzGAQgASgNSAOIAQFCDwoNX3Byb21vdGlv",
            "bl9pZEIICgZfdGltZXNCBgoEX3VpZEIOCgxfdG90YWxfdGltZXMiOwoNTG90",
            "dGVyeVJ1blJFURIZCgxwcm9tb3Rpb25faWQYASABKAVIAIgBAUIPCg1fcHJv",
            "bW90aW9uX2lkIsEBCg1Mb3R0ZXJ5UnVuUlNQEhkKDHByb21vdGlvbl9pZBgB",
            "IAEoBUgAiAEBEhAKA3VpZBgCIAEoA0gBiAEBEh0KBGl0ZW0YAyABKAsyCi5Q",
            "cml6ZUl0ZW1IAogBARIXCgpsZWZ0X3RpbWVzGAQgASgNSAOIAQESEQoEY29k",
            "ZRgFIAEoBUgEiAEBQg8KDV9wcm9tb3Rpb25faWRCBgoEX3VpZEIHCgVfaXRl",
            "bUINCgtfbGVmdF90aW1lc0IHCgVfY29kZSKbAQoJTHVja3lVc2VyEhAKA3Vp",
            "ZBgBIAEoA0gAiAEBEhYKCXVzZXJfbmFtZRgCIAEoCUgBiAEBEhcKCmx1Y2t5",
            "X3RpbWUYAyABKA1IAogBARIdCgRpdGVtGAQgASgLMgouUHJpemVJdGVtSAOI",
            "AQFCBgoEX3VpZEIMCgpfdXNlcl9uYW1lQg0KC19sdWNreV90aW1lQgcKBV9p",
            "dGVtIkEKE0dldEx1Y2t5VXNlckxpc3RSRVESGQoMcHJvbW90aW9uX2lkGAEg",
            "ASgFSACIAQFCDwoNX3Byb21vdGlvbl9pZCJcChNHZXRMdWNreVVzZXJMaXN0",
            "UlNQEhkKDHByb21vdGlvbl9pZBgBIAEoBUgAiAEBEhkKBXVzZXJzGAIgAygL",
            "MgouTHVja3lVc2VyQg8KDV9wcm9tb3Rpb25faWQqtgEKC1ByaXplSXRlbUlE",
            "Eh8KG1BSSVpFX0lURU1fTkFNRV8zMF9ESUFNT05EUxAAEiAKHFBSSVpFX0lU",
            "RU1fTkFNRV8xODBfRElBTU9ORFMQAhIgChxQUklaRV9JVEVNX05BTUVfMjgw",
            "X0RJQU1PTkRTEAMSIAocUFJJWkVfSVRFTV9OQU1FXzU4MF9ESUFNT05EUxAE",
            "EiAKHFBSSVpFX0lURU1fTkFNRV84ODBfRElBTU9ORFMQBSotCgtQcm9tb3Rp",
            "b25JRBIeChpQUk9NT1RJT05fSURfMjAxN0NIUklTVE1BUxAAKmcKD1Byb21v",
            "dGlvblN0YXR1cxIZChVQUk9NT1RJT05fU1RBVFVTX05PTkUQABIbChdQUk9N",
            "T1RJT05fU1RBVFVTX09OTElORRABEhwKGFBST01PVElPTl9TVEFUVVNfT0ZG",
            "TElORRACKosBCg9Vc2VyUHJpemVTdGF0dXMSGgoWVVNFUl9QUklaRV9TVEFU",
            "VVNfTk9ORRAAEhoKFlVTRVJfUFJJWkVfU1RBVFVTX01JU1MQARIbChdVU0VS",
            "X1BSSVpFX1NUQVRVU19BV0FSRBACEiMKH1VTRVJfUFJJWkVfU1RBVFVTX1VT",
            "RVJfUkVDVklDRUQQA0IYWgUvZ29wYqoCDlRleGFzLlByb3RvY29sYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Texas.Protocol.PrizeItemID), typeof(global::Texas.Protocol.PromotionID), typeof(global::Texas.Protocol.PromotionStatus), typeof(global::Texas.Protocol.UserPrizeStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.PrizeItem), global::Texas.Protocol.PrizeItem.Parser, new[]{ "PromotionId", "PrizeItemId", "ItemName" }, new[]{ "PromotionId", "PrizeItemId", "ItemName" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.PromotionLeftTimesREQ), global::Texas.Protocol.PromotionLeftTimesREQ.Parser, new[]{ "PromotionId" }, new[]{ "PromotionId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.PromotionLeftTimesRSP), global::Texas.Protocol.PromotionLeftTimesRSP.Parser, new[]{ "PromotionId", "LeftTimes", "Uid" }, new[]{ "PromotionId", "LeftTimes", "Uid" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.ReceivceLeftTimesPush), global::Texas.Protocol.ReceivceLeftTimesPush.Parser, new[]{ "PromotionId", "Times", "Uid", "TotalTimes" }, new[]{ "PromotionId", "Times", "Uid", "TotalTimes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.LotteryRunREQ), global::Texas.Protocol.LotteryRunREQ.Parser, new[]{ "PromotionId" }, new[]{ "PromotionId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.LotteryRunRSP), global::Texas.Protocol.LotteryRunRSP.Parser, new[]{ "PromotionId", "Uid", "Item", "LeftTimes", "Code" }, new[]{ "PromotionId", "Uid", "Item", "LeftTimes", "Code" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.LuckyUser), global::Texas.Protocol.LuckyUser.Parser, new[]{ "Uid", "UserName", "LuckyTime", "Item" }, new[]{ "Uid", "UserName", "LuckyTime", "Item" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.GetLuckyUserListREQ), global::Texas.Protocol.GetLuckyUserListREQ.Parser, new[]{ "PromotionId" }, new[]{ "PromotionId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Texas.Protocol.GetLuckyUserListRSP), global::Texas.Protocol.GetLuckyUserListRSP.Parser, new[]{ "PromotionId", "Users" }, new[]{ "PromotionId" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PrizeItemID {
    [pbr::OriginalName("PRIZE_ITEM_NAME_30_DIAMONDS")] PrizeItemName30Diamonds = 0,
    [pbr::OriginalName("PRIZE_ITEM_NAME_180_DIAMONDS")] PrizeItemName180Diamonds = 2,
    [pbr::OriginalName("PRIZE_ITEM_NAME_280_DIAMONDS")] PrizeItemName280Diamonds = 3,
    [pbr::OriginalName("PRIZE_ITEM_NAME_580_DIAMONDS")] PrizeItemName580Diamonds = 4,
    [pbr::OriginalName("PRIZE_ITEM_NAME_880_DIAMONDS")] PrizeItemName880Diamonds = 5,
  }

  public enum PromotionID {
    /// <summary>
    ///2017圣诞抽奖
    /// </summary>
    [pbr::OriginalName("PROMOTION_ID_2017CHRISTMAS")] _2017Christmas = 0,
  }

  public enum PromotionStatus {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("PROMOTION_STATUS_NONE")] None = 0,
    /// <summary>
    ///上线 
    /// </summary>
    [pbr::OriginalName("PROMOTION_STATUS_ONLINE")] Online = 1,
    /// <summary>
    ///下线
    /// </summary>
    [pbr::OriginalName("PROMOTION_STATUS_OFFLINE")] Offline = 2,
  }

  public enum UserPrizeStatus {
    /// <summary>
    ///未发奖
    /// </summary>
    [pbr::OriginalName("USER_PRIZE_STATUS_NONE")] None = 0,
    /// <summary>
    ///未中奖
    /// </summary>
    [pbr::OriginalName("USER_PRIZE_STATUS_MISS")] Miss = 1,
    /// <summary>
    ///已发奖,用户未领奖
    /// </summary>
    [pbr::OriginalName("USER_PRIZE_STATUS_AWARD")] Award = 2,
    /// <summary>
    ///用户已经领奖
    /// </summary>
    [pbr::OriginalName("USER_PRIZE_STATUS_USER_RECVICED")] UserRecviced = 3,
  }

  #endregion

  #region Messages
  public sealed partial class PrizeItem : pb::IMessage<PrizeItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PrizeItem> _parser = new pb::MessageParser<PrizeItem>(() => new PrizeItem());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PrizeItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PrizeItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PrizeItem(PrizeItem other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      prizeItemId_ = other.prizeItemId_;
      itemName_ = other.itemName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PrizeItem Clone() {
      return new PrizeItem(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "prize_item_id" field.</summary>
    public const int PrizeItemIdFieldNumber = 2;
    private readonly static int PrizeItemIdDefaultValue = 0;

    private int prizeItemId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PrizeItemId {
      get { if ((_hasBits0 & 2) != 0) { return prizeItemId_; } else { return PrizeItemIdDefaultValue; } }
      set {
        _hasBits0 |= 2;
        prizeItemId_ = value;
      }
    }
    /// <summary>Gets whether the "prize_item_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPrizeItemId {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "prize_item_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPrizeItemId() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "item_name" field.</summary>
    public const int ItemNameFieldNumber = 3;
    private readonly static string ItemNameDefaultValue = "";

    private string itemName_;
    /// <summary>
    ///名字为PrizeItemID中key的名字
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ItemName {
      get { return itemName_ ?? ItemNameDefaultValue; }
      set {
        itemName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "item_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasItemName {
      get { return itemName_ != null; }
    }
    /// <summary>Clears the value of the "item_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearItemName() {
      itemName_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PrizeItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PrizeItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      if (PrizeItemId != other.PrizeItemId) return false;
      if (ItemName != other.ItemName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (HasPrizeItemId) hash ^= PrizeItemId.GetHashCode();
      if (HasItemName) hash ^= ItemName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasPrizeItemId) {
        output.WriteRawTag(16);
        output.WriteInt32(PrizeItemId);
      }
      if (HasItemName) {
        output.WriteRawTag(26);
        output.WriteString(ItemName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasPrizeItemId) {
        output.WriteRawTag(16);
        output.WriteInt32(PrizeItemId);
      }
      if (HasItemName) {
        output.WriteRawTag(26);
        output.WriteString(ItemName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (HasPrizeItemId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PrizeItemId);
      }
      if (HasItemName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ItemName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PrizeItem other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      if (other.HasPrizeItemId) {
        PrizeItemId = other.PrizeItemId;
      }
      if (other.HasItemName) {
        ItemName = other.ItemName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            PrizeItemId = input.ReadInt32();
            break;
          }
          case 26: {
            ItemName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            PrizeItemId = input.ReadInt32();
            break;
          }
          case 26: {
            ItemName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///请求剩余次数
  /// </summary>
  public sealed partial class PromotionLeftTimesREQ : pb::IMessage<PromotionLeftTimesREQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PromotionLeftTimesREQ> _parser = new pb::MessageParser<PromotionLeftTimesREQ>(() => new PromotionLeftTimesREQ());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PromotionLeftTimesREQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PromotionLeftTimesREQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PromotionLeftTimesREQ(PromotionLeftTimesREQ other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PromotionLeftTimesREQ Clone() {
      return new PromotionLeftTimesREQ(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PromotionLeftTimesREQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PromotionLeftTimesREQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PromotionLeftTimesREQ other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class PromotionLeftTimesRSP : pb::IMessage<PromotionLeftTimesRSP>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PromotionLeftTimesRSP> _parser = new pb::MessageParser<PromotionLeftTimesRSP>(() => new PromotionLeftTimesRSP());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PromotionLeftTimesRSP> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PromotionLeftTimesRSP() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PromotionLeftTimesRSP(PromotionLeftTimesRSP other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      leftTimes_ = other.leftTimes_;
      uid_ = other.uid_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PromotionLeftTimesRSP Clone() {
      return new PromotionLeftTimesRSP(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "left_times" field.</summary>
    public const int LeftTimesFieldNumber = 2;
    private readonly static uint LeftTimesDefaultValue = 0;

    private uint leftTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LeftTimes {
      get { if ((_hasBits0 & 2) != 0) { return leftTimes_; } else { return LeftTimesDefaultValue; } }
      set {
        _hasBits0 |= 2;
        leftTimes_ = value;
      }
    }
    /// <summary>Gets whether the "left_times" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLeftTimes {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "left_times" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLeftTimes() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 3;
    private readonly static long UidDefaultValue = 0L;

    private long uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uid {
      get { if ((_hasBits0 & 4) != 0) { return uid_; } else { return UidDefaultValue; } }
      set {
        _hasBits0 |= 4;
        uid_ = value;
      }
    }
    /// <summary>Gets whether the "uid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUid {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "uid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUid() {
      _hasBits0 &= ~4;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PromotionLeftTimesRSP);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PromotionLeftTimesRSP other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      if (LeftTimes != other.LeftTimes) return false;
      if (Uid != other.Uid) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (HasLeftTimes) hash ^= LeftTimes.GetHashCode();
      if (HasUid) hash ^= Uid.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasLeftTimes) {
        output.WriteRawTag(16);
        output.WriteUInt32(LeftTimes);
      }
      if (HasUid) {
        output.WriteRawTag(24);
        output.WriteInt64(Uid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasLeftTimes) {
        output.WriteRawTag(16);
        output.WriteUInt32(LeftTimes);
      }
      if (HasUid) {
        output.WriteRawTag(24);
        output.WriteInt64(Uid);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (HasLeftTimes) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LeftTimes);
      }
      if (HasUid) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PromotionLeftTimesRSP other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      if (other.HasLeftTimes) {
        LeftTimes = other.LeftTimes;
      }
      if (other.HasUid) {
        Uid = other.Uid;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            LeftTimes = input.ReadUInt32();
            break;
          }
          case 24: {
            Uid = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            LeftTimes = input.ReadUInt32();
            break;
          }
          case 24: {
            Uid = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///推送得到的抽奖次数
  /// </summary>
  public sealed partial class ReceivceLeftTimesPush : pb::IMessage<ReceivceLeftTimesPush>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ReceivceLeftTimesPush> _parser = new pb::MessageParser<ReceivceLeftTimesPush>(() => new ReceivceLeftTimesPush());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ReceivceLeftTimesPush> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReceivceLeftTimesPush() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReceivceLeftTimesPush(ReceivceLeftTimesPush other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      times_ = other.times_;
      uid_ = other.uid_;
      totalTimes_ = other.totalTimes_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ReceivceLeftTimesPush Clone() {
      return new ReceivceLeftTimesPush(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "times" field.</summary>
    public const int TimesFieldNumber = 2;
    private readonly static uint TimesDefaultValue = 0;

    private uint times_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Times {
      get { if ((_hasBits0 & 2) != 0) { return times_; } else { return TimesDefaultValue; } }
      set {
        _hasBits0 |= 2;
        times_ = value;
      }
    }
    /// <summary>Gets whether the "times" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTimes {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "times" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTimes() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 3;
    private readonly static long UidDefaultValue = 0L;

    private long uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uid {
      get { if ((_hasBits0 & 4) != 0) { return uid_; } else { return UidDefaultValue; } }
      set {
        _hasBits0 |= 4;
        uid_ = value;
      }
    }
    /// <summary>Gets whether the "uid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUid {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "uid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUid() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "total_times" field.</summary>
    public const int TotalTimesFieldNumber = 4;
    private readonly static uint TotalTimesDefaultValue = 0;

    private uint totalTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalTimes {
      get { if ((_hasBits0 & 8) != 0) { return totalTimes_; } else { return TotalTimesDefaultValue; } }
      set {
        _hasBits0 |= 8;
        totalTimes_ = value;
      }
    }
    /// <summary>Gets whether the "total_times" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasTotalTimes {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "total_times" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearTotalTimes() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ReceivceLeftTimesPush);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ReceivceLeftTimesPush other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      if (Times != other.Times) return false;
      if (Uid != other.Uid) return false;
      if (TotalTimes != other.TotalTimes) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (HasTimes) hash ^= Times.GetHashCode();
      if (HasUid) hash ^= Uid.GetHashCode();
      if (HasTotalTimes) hash ^= TotalTimes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasTimes) {
        output.WriteRawTag(16);
        output.WriteUInt32(Times);
      }
      if (HasUid) {
        output.WriteRawTag(24);
        output.WriteInt64(Uid);
      }
      if (HasTotalTimes) {
        output.WriteRawTag(32);
        output.WriteUInt32(TotalTimes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasTimes) {
        output.WriteRawTag(16);
        output.WriteUInt32(Times);
      }
      if (HasUid) {
        output.WriteRawTag(24);
        output.WriteInt64(Uid);
      }
      if (HasTotalTimes) {
        output.WriteRawTag(32);
        output.WriteUInt32(TotalTimes);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (HasTimes) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Times);
      }
      if (HasUid) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (HasTotalTimes) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalTimes);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ReceivceLeftTimesPush other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      if (other.HasTimes) {
        Times = other.Times;
      }
      if (other.HasUid) {
        Uid = other.Uid;
      }
      if (other.HasTotalTimes) {
        TotalTimes = other.TotalTimes;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            Times = input.ReadUInt32();
            break;
          }
          case 24: {
            Uid = input.ReadInt64();
            break;
          }
          case 32: {
            TotalTimes = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            Times = input.ReadUInt32();
            break;
          }
          case 24: {
            Uid = input.ReadInt64();
            break;
          }
          case 32: {
            TotalTimes = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///开始抽奖
  /// </summary>
  public sealed partial class LotteryRunREQ : pb::IMessage<LotteryRunREQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LotteryRunREQ> _parser = new pb::MessageParser<LotteryRunREQ>(() => new LotteryRunREQ());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LotteryRunREQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LotteryRunREQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LotteryRunREQ(LotteryRunREQ other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LotteryRunREQ Clone() {
      return new LotteryRunREQ(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LotteryRunREQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LotteryRunREQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LotteryRunREQ other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LotteryRunRSP : pb::IMessage<LotteryRunRSP>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LotteryRunRSP> _parser = new pb::MessageParser<LotteryRunRSP>(() => new LotteryRunRSP());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LotteryRunRSP> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LotteryRunRSP() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LotteryRunRSP(LotteryRunRSP other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      uid_ = other.uid_;
      item_ = other.item_ != null ? other.item_.Clone() : null;
      leftTimes_ = other.leftTimes_;
      code_ = other.code_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LotteryRunRSP Clone() {
      return new LotteryRunRSP(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private readonly static long UidDefaultValue = 0L;

    private long uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uid {
      get { if ((_hasBits0 & 2) != 0) { return uid_; } else { return UidDefaultValue; } }
      set {
        _hasBits0 |= 2;
        uid_ = value;
      }
    }
    /// <summary>Gets whether the "uid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUid {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "uid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUid() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 3;
    private global::Texas.Protocol.PrizeItem item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Texas.Protocol.PrizeItem Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    /// <summary>Field number for the "left_times" field.</summary>
    public const int LeftTimesFieldNumber = 4;
    private readonly static uint LeftTimesDefaultValue = 0;

    private uint leftTimes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LeftTimes {
      get { if ((_hasBits0 & 4) != 0) { return leftTimes_; } else { return LeftTimesDefaultValue; } }
      set {
        _hasBits0 |= 4;
        leftTimes_ = value;
      }
    }
    /// <summary>Gets whether the "left_times" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLeftTimes {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "left_times" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLeftTimes() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "code" field.</summary>
    public const int CodeFieldNumber = 5;
    private readonly static int CodeDefaultValue = 0;

    private int code_;
    /// <summary>
    /// 0.成功 -1.没有次数 -2.活动已过期 -3.活动没开始 -4.抽奖失败
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Code {
      get { if ((_hasBits0 & 8) != 0) { return code_; } else { return CodeDefaultValue; } }
      set {
        _hasBits0 |= 8;
        code_ = value;
      }
    }
    /// <summary>Gets whether the "code" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCode {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "code" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCode() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LotteryRunRSP);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LotteryRunRSP other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      if (Uid != other.Uid) return false;
      if (!object.Equals(Item, other.Item)) return false;
      if (LeftTimes != other.LeftTimes) return false;
      if (Code != other.Code) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (HasUid) hash ^= Uid.GetHashCode();
      if (item_ != null) hash ^= Item.GetHashCode();
      if (HasLeftTimes) hash ^= LeftTimes.GetHashCode();
      if (HasCode) hash ^= Code.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasUid) {
        output.WriteRawTag(16);
        output.WriteInt64(Uid);
      }
      if (item_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Item);
      }
      if (HasLeftTimes) {
        output.WriteRawTag(32);
        output.WriteUInt32(LeftTimes);
      }
      if (HasCode) {
        output.WriteRawTag(40);
        output.WriteInt32(Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (HasUid) {
        output.WriteRawTag(16);
        output.WriteInt64(Uid);
      }
      if (item_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Item);
      }
      if (HasLeftTimes) {
        output.WriteRawTag(32);
        output.WriteUInt32(LeftTimes);
      }
      if (HasCode) {
        output.WriteRawTag(40);
        output.WriteInt32(Code);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (HasUid) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (HasLeftTimes) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LeftTimes);
      }
      if (HasCode) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LotteryRunRSP other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      if (other.HasUid) {
        Uid = other.Uid;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::Texas.Protocol.PrizeItem();
        }
        Item.MergeFrom(other.Item);
      }
      if (other.HasLeftTimes) {
        LeftTimes = other.LeftTimes;
      }
      if (other.HasCode) {
        Code = other.Code;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            Uid = input.ReadInt64();
            break;
          }
          case 26: {
            if (item_ == null) {
              Item = new global::Texas.Protocol.PrizeItem();
            }
            input.ReadMessage(Item);
            break;
          }
          case 32: {
            LeftTimes = input.ReadUInt32();
            break;
          }
          case 40: {
            Code = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 16: {
            Uid = input.ReadInt64();
            break;
          }
          case 26: {
            if (item_ == null) {
              Item = new global::Texas.Protocol.PrizeItem();
            }
            input.ReadMessage(Item);
            break;
          }
          case 32: {
            LeftTimes = input.ReadUInt32();
            break;
          }
          case 40: {
            Code = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class LuckyUser : pb::IMessage<LuckyUser>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<LuckyUser> _parser = new pb::MessageParser<LuckyUser>(() => new LuckyUser());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<LuckyUser> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LuckyUser() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LuckyUser(LuckyUser other) : this() {
      _hasBits0 = other._hasBits0;
      uid_ = other.uid_;
      userName_ = other.userName_;
      luckyTime_ = other.luckyTime_;
      item_ = other.item_ != null ? other.item_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public LuckyUser Clone() {
      return new LuckyUser(this);
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 1;
    private readonly static long UidDefaultValue = 0L;

    private long uid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Uid {
      get { if ((_hasBits0 & 1) != 0) { return uid_; } else { return UidDefaultValue; } }
      set {
        _hasBits0 |= 1;
        uid_ = value;
      }
    }
    /// <summary>Gets whether the "uid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUid {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "uid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUid() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "user_name" field.</summary>
    public const int UserNameFieldNumber = 2;
    private readonly static string UserNameDefaultValue = "";

    private string userName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserName {
      get { return userName_ ?? UserNameDefaultValue; }
      set {
        userName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "user_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasUserName {
      get { return userName_ != null; }
    }
    /// <summary>Clears the value of the "user_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearUserName() {
      userName_ = null;
    }

    /// <summary>Field number for the "lucky_time" field.</summary>
    public const int LuckyTimeFieldNumber = 3;
    private readonly static uint LuckyTimeDefaultValue = 0;

    private uint luckyTime_;
    /// <summary>
    ///得奖时间
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LuckyTime {
      get { if ((_hasBits0 & 2) != 0) { return luckyTime_; } else { return LuckyTimeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        luckyTime_ = value;
      }
    }
    /// <summary>Gets whether the "lucky_time" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasLuckyTime {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "lucky_time" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearLuckyTime() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "item" field.</summary>
    public const int ItemFieldNumber = 4;
    private global::Texas.Protocol.PrizeItem item_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Texas.Protocol.PrizeItem Item {
      get { return item_; }
      set {
        item_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as LuckyUser);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(LuckyUser other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Uid != other.Uid) return false;
      if (UserName != other.UserName) return false;
      if (LuckyTime != other.LuckyTime) return false;
      if (!object.Equals(Item, other.Item)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasUid) hash ^= Uid.GetHashCode();
      if (HasUserName) hash ^= UserName.GetHashCode();
      if (HasLuckyTime) hash ^= LuckyTime.GetHashCode();
      if (item_ != null) hash ^= Item.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasUid) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (HasUserName) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (HasLuckyTime) {
        output.WriteRawTag(24);
        output.WriteUInt32(LuckyTime);
      }
      if (item_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Item);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasUid) {
        output.WriteRawTag(8);
        output.WriteInt64(Uid);
      }
      if (HasUserName) {
        output.WriteRawTag(18);
        output.WriteString(UserName);
      }
      if (HasLuckyTime) {
        output.WriteRawTag(24);
        output.WriteUInt32(LuckyTime);
      }
      if (item_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Item);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasUid) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Uid);
      }
      if (HasUserName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserName);
      }
      if (HasLuckyTime) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LuckyTime);
      }
      if (item_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Item);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(LuckyUser other) {
      if (other == null) {
        return;
      }
      if (other.HasUid) {
        Uid = other.Uid;
      }
      if (other.HasUserName) {
        UserName = other.UserName;
      }
      if (other.HasLuckyTime) {
        LuckyTime = other.LuckyTime;
      }
      if (other.item_ != null) {
        if (item_ == null) {
          Item = new global::Texas.Protocol.PrizeItem();
        }
        Item.MergeFrom(other.Item);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 24: {
            LuckyTime = input.ReadUInt32();
            break;
          }
          case 34: {
            if (item_ == null) {
              Item = new global::Texas.Protocol.PrizeItem();
            }
            input.ReadMessage(Item);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Uid = input.ReadInt64();
            break;
          }
          case 18: {
            UserName = input.ReadString();
            break;
          }
          case 24: {
            LuckyTime = input.ReadUInt32();
            break;
          }
          case 34: {
            if (item_ == null) {
              Item = new global::Texas.Protocol.PrizeItem();
            }
            input.ReadMessage(Item);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///当前得奖人列表
  /// </summary>
  public sealed partial class GetLuckyUserListREQ : pb::IMessage<GetLuckyUserListREQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetLuckyUserListREQ> _parser = new pb::MessageParser<GetLuckyUserListREQ>(() => new GetLuckyUserListREQ());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetLuckyUserListREQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLuckyUserListREQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLuckyUserListREQ(GetLuckyUserListREQ other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLuckyUserListREQ Clone() {
      return new GetLuckyUserListREQ(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetLuckyUserListREQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetLuckyUserListREQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetLuckyUserListREQ other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetLuckyUserListRSP : pb::IMessage<GetLuckyUserListRSP>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetLuckyUserListRSP> _parser = new pb::MessageParser<GetLuckyUserListRSP>(() => new GetLuckyUserListRSP());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GetLuckyUserListRSP> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Texas.Protocol.PromotionsReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLuckyUserListRSP() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLuckyUserListRSP(GetLuckyUserListRSP other) : this() {
      _hasBits0 = other._hasBits0;
      promotionId_ = other.promotionId_;
      users_ = other.users_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GetLuckyUserListRSP Clone() {
      return new GetLuckyUserListRSP(this);
    }

    /// <summary>Field number for the "promotion_id" field.</summary>
    public const int PromotionIdFieldNumber = 1;
    private readonly static int PromotionIdDefaultValue = 0;

    private int promotionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int PromotionId {
      get { if ((_hasBits0 & 1) != 0) { return promotionId_; } else { return PromotionIdDefaultValue; } }
      set {
        _hasBits0 |= 1;
        promotionId_ = value;
      }
    }
    /// <summary>Gets whether the "promotion_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPromotionId {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "promotion_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPromotionId() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "users" field.</summary>
    public const int UsersFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Texas.Protocol.LuckyUser> _repeated_users_codec
        = pb::FieldCodec.ForMessage(18, global::Texas.Protocol.LuckyUser.Parser);
    private readonly pbc::RepeatedField<global::Texas.Protocol.LuckyUser> users_ = new pbc::RepeatedField<global::Texas.Protocol.LuckyUser>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Texas.Protocol.LuckyUser> Users {
      get { return users_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GetLuckyUserListRSP);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GetLuckyUserListRSP other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PromotionId != other.PromotionId) return false;
      if(!users_.Equals(other.users_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPromotionId) hash ^= PromotionId.GetHashCode();
      hash ^= users_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      users_.WriteTo(output, _repeated_users_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPromotionId) {
        output.WriteRawTag(8);
        output.WriteInt32(PromotionId);
      }
      users_.WriteTo(ref output, _repeated_users_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPromotionId) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PromotionId);
      }
      size += users_.CalculateSize(_repeated_users_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GetLuckyUserListRSP other) {
      if (other == null) {
        return;
      }
      if (other.HasPromotionId) {
        PromotionId = other.PromotionId;
      }
      users_.Add(other.users_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 18: {
            users_.AddEntriesFrom(input, _repeated_users_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PromotionId = input.ReadInt32();
            break;
          }
          case 18: {
            users_.AddEntriesFrom(ref input, _repeated_users_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
