// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protowrap.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace GameService.Protocol {

  /// <summary>Holder for reflection information generated from protowrap.proto</summary>
  public static partial class ProtowrapReflection {

    #region Descriptor
    /// <summary>File descriptor for protowrap.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtowrapReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wcm90b3dyYXAucHJvdG8iggEKC1Byb3RvV3JhcEdvEgsKA3ZlchgBIAEo",
            "BRIYCgJvcBgCIAEoDjIMLk1lc3NhZ2VUeXBlEgsKA3NlcRgDIAEoBRIPCgdz",
            "dWNjZXNzGAQgASgIEhQKB2NvbW1hbmQYBSABKAlIAIgBARIMCgRib2R5GAYg",
            "ASgMQgoKCF9jb21tYW5kKjkKC01lc3NhZ2VUeXBlEhMKD01lc3NhZ2VfUkVR",
            "VUVTVBAAEhUKEU1lc3NhZ2VfQlJPQURDQVNUEAFCIFoHL3BicHBnb6oCFEdh",
            "bWVTZXJ2aWNlLlByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::GameService.Protocol.MessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::GameService.Protocol.ProtoWrapGo), global::GameService.Protocol.ProtoWrapGo.Parser, new[]{ "Ver", "Op", "Seq", "Success", "Command", "Body" }, new[]{ "Command" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    [pbr::OriginalName("Message_REQUEST")] MessageRequest = 0,
    [pbr::OriginalName("Message_BROADCAST")] MessageBroadcast = 1,
  }

  #endregion

  #region Messages
  public sealed partial class ProtoWrapGo : pb::IMessage<ProtoWrapGo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ProtoWrapGo> _parser = new pb::MessageParser<ProtoWrapGo>(() => new ProtoWrapGo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ProtoWrapGo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::GameService.Protocol.ProtowrapReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoWrapGo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoWrapGo(ProtoWrapGo other) : this() {
      ver_ = other.ver_;
      op_ = other.op_;
      seq_ = other.seq_;
      success_ = other.success_;
      command_ = other.command_;
      body_ = other.body_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ProtoWrapGo Clone() {
      return new ProtoWrapGo(this);
    }

    /// <summary>Field number for the "ver" field.</summary>
    public const int VerFieldNumber = 1;
    private int ver_;
    /// <summary>
    /// version
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Ver {
      get { return ver_; }
      set {
        ver_ = value;
      }
    }

    /// <summary>Field number for the "op" field.</summary>
    public const int OpFieldNumber = 2;
    private global::GameService.Protocol.MessageType op_ = global::GameService.Protocol.MessageType.MessageRequest;
    /// <summary>
    /// option/action
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::GameService.Protocol.MessageType Op {
      get { return op_; }
      set {
        op_ = value;
      }
    }

    /// <summary>Field number for the "seq" field.</summary>
    public const int SeqFieldNumber = 3;
    private int seq_;
    /// <summary>
    /// sequence
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Seq {
      get { return seq_; }
      set {
        seq_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 4;
    private bool success_;
    /// <summary>
    /// 请求是否成功
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 5;
    private readonly static string CommandDefaultValue = "";

    private string command_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Command {
      get { return command_ ?? CommandDefaultValue; }
      set {
        command_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "command" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCommand {
      get { return command_ != null; }
    }
    /// <summary>Clears the value of the "command" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCommand() {
      command_ = null;
    }

    /// <summary>Field number for the "body" field.</summary>
    public const int BodyFieldNumber = 6;
    private pb::ByteString body_ = pb::ByteString.Empty;
    /// <summary>
    /// proto bytes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Body {
      get { return body_; }
      set {
        body_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ProtoWrapGo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ProtoWrapGo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Ver != other.Ver) return false;
      if (Op != other.Op) return false;
      if (Seq != other.Seq) return false;
      if (Success != other.Success) return false;
      if (Command != other.Command) return false;
      if (Body != other.Body) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Ver != 0) hash ^= Ver.GetHashCode();
      if (Op != global::GameService.Protocol.MessageType.MessageRequest) hash ^= Op.GetHashCode();
      if (Seq != 0) hash ^= Seq.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      if (HasCommand) hash ^= Command.GetHashCode();
      if (Body.Length != 0) hash ^= Body.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Ver != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Ver);
      }
      if (Op != global::GameService.Protocol.MessageType.MessageRequest) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Op);
      }
      if (Seq != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seq);
      }
      if (Success != false) {
        output.WriteRawTag(32);
        output.WriteBool(Success);
      }
      if (HasCommand) {
        output.WriteRawTag(42);
        output.WriteString(Command);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Ver != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Ver);
      }
      if (Op != global::GameService.Protocol.MessageType.MessageRequest) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Op);
      }
      if (Seq != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Seq);
      }
      if (Success != false) {
        output.WriteRawTag(32);
        output.WriteBool(Success);
      }
      if (HasCommand) {
        output.WriteRawTag(42);
        output.WriteString(Command);
      }
      if (Body.Length != 0) {
        output.WriteRawTag(50);
        output.WriteBytes(Body);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Ver != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ver);
      }
      if (Op != global::GameService.Protocol.MessageType.MessageRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Op);
      }
      if (Seq != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Seq);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      if (HasCommand) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Command);
      }
      if (Body.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Body);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ProtoWrapGo other) {
      if (other == null) {
        return;
      }
      if (other.Ver != 0) {
        Ver = other.Ver;
      }
      if (other.Op != global::GameService.Protocol.MessageType.MessageRequest) {
        Op = other.Op;
      }
      if (other.Seq != 0) {
        Seq = other.Seq;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      if (other.HasCommand) {
        Command = other.Command;
      }
      if (other.Body.Length != 0) {
        Body = other.Body;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Ver = input.ReadInt32();
            break;
          }
          case 16: {
            Op = (global::GameService.Protocol.MessageType) input.ReadEnum();
            break;
          }
          case 24: {
            Seq = input.ReadInt32();
            break;
          }
          case 32: {
            Success = input.ReadBool();
            break;
          }
          case 42: {
            Command = input.ReadString();
            break;
          }
          case 50: {
            Body = input.ReadBytes();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Ver = input.ReadInt32();
            break;
          }
          case 16: {
            Op = (global::GameService.Protocol.MessageType) input.ReadEnum();
            break;
          }
          case 24: {
            Seq = input.ReadInt32();
            break;
          }
          case 32: {
            Success = input.ReadBool();
            break;
          }
          case 42: {
            Command = input.ReadString();
            break;
          }
          case 50: {
            Body = input.ReadBytes();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
